"""empty message

Revision ID: e53465c9b54f
Revises: 
Create Date: 2022-04-04 23:54:21.909907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53465c9b54f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('editora', sa.String(length=255), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=False),
    sa.Column('autores', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Obra')
    # ### end Alembic commands ###
